//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsuariosTest.MonederoService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecargaBE", Namespace="http://schemas.datacontract.org/2004/07/DSD.BusinessEntity")]
    [System.SerializableAttribute()]
    public partial class RecargaBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MontoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperacionBancoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoCliente {
            get {
                return this.CodigoClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoClienteField, value) != true)) {
                    this.CodigoClienteField = value;
                    this.RaisePropertyChanged("CodigoCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Monto {
            get {
                return this.MontoField;
            }
            set {
                if ((this.MontoField.Equals(value) != true)) {
                    this.MontoField = value;
                    this.RaisePropertyChanged("Monto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperacionBanco {
            get {
                return this.OperacionBancoField;
            }
            set {
                if ((object.ReferenceEquals(this.OperacionBancoField, value) != true)) {
                    this.OperacionBancoField = value;
                    this.RaisePropertyChanged("OperacionBanco");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MovimientoBE", Namespace="http://schemas.datacontract.org/2004/07/DSD.BusinessEntity")]
    [System.SerializableAttribute()]
    public partial class MovimientoBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MontoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OperacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperacionBancoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoCliente {
            get {
                return this.CodigoClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoClienteField, value) != true)) {
                    this.CodigoClienteField = value;
                    this.RaisePropertyChanged("CodigoCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaField, value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Monto {
            get {
                return this.MontoField;
            }
            set {
                if ((this.MontoField.Equals(value) != true)) {
                    this.MontoField = value;
                    this.RaisePropertyChanged("Monto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Operacion {
            get {
                return this.OperacionField;
            }
            set {
                if ((this.OperacionField.Equals(value) != true)) {
                    this.OperacionField = value;
                    this.RaisePropertyChanged("Operacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperacionBanco {
            get {
                return this.OperacionBancoField;
            }
            set {
                if ((object.ReferenceEquals(this.OperacionBancoField, value) != true)) {
                    this.OperacionBancoField = value;
                    this.RaisePropertyChanged("OperacionBanco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExtornoBE", Namespace="http://schemas.datacontract.org/2004/07/DSD.BusinessEntity")]
    [System.SerializableAttribute()]
    public partial class ExtornoBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MontoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperacionBancoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperacionBancoExtornoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoCliente {
            get {
                return this.CodigoClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoClienteField, value) != true)) {
                    this.CodigoClienteField = value;
                    this.RaisePropertyChanged("CodigoCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Monto {
            get {
                return this.MontoField;
            }
            set {
                if ((this.MontoField.Equals(value) != true)) {
                    this.MontoField = value;
                    this.RaisePropertyChanged("Monto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperacionBanco {
            get {
                return this.OperacionBancoField;
            }
            set {
                if ((object.ReferenceEquals(this.OperacionBancoField, value) != true)) {
                    this.OperacionBancoField = value;
                    this.RaisePropertyChanged("OperacionBanco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperacionBancoExtorno {
            get {
                return this.OperacionBancoExtornoField;
            }
            set {
                if ((object.ReferenceEquals(this.OperacionBancoExtornoField, value) != true)) {
                    this.OperacionBancoExtornoField = value;
                    this.RaisePropertyChanged("OperacionBancoExtorno");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PagoBE", Namespace="http://schemas.datacontract.org/2004/07/DSD.BusinessEntity")]
    [System.SerializableAttribute()]
    public partial class PagoBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MontoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperacionBancoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoCliente {
            get {
                return this.CodigoClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoClienteField, value) != true)) {
                    this.CodigoClienteField = value;
                    this.RaisePropertyChanged("CodigoCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Monto {
            get {
                return this.MontoField;
            }
            set {
                if ((this.MontoField.Equals(value) != true)) {
                    this.MontoField = value;
                    this.RaisePropertyChanged("Monto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperacionBanco {
            get {
                return this.OperacionBancoField;
            }
            set {
                if ((object.ReferenceEquals(this.OperacionBancoField, value) != true)) {
                    this.OperacionBancoField = value;
                    this.RaisePropertyChanged("OperacionBanco");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaldoBE", Namespace="http://schemas.datacontract.org/2004/07/DSD.BusinessEntity")]
    [System.SerializableAttribute()]
    public partial class SaldoBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoClienteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoCliente {
            get {
                return this.CodigoClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoClienteField, value) != true)) {
                    this.CodigoClienteField = value;
                    this.RaisePropertyChanged("CodigoCliente");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MonederoService.IMonederosService")]
    public interface IMonederosService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonederosService/Recargar", ReplyAction="http://tempuri.org/IMonederosService/RecargarResponse")]
        MonederoService.MovimientoBE Recargar(MonederoService.RecargaBE recarga);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonederosService/Recargar", ReplyAction="http://tempuri.org/IMonederosService/RecargarResponse")]
        System.Threading.Tasks.Task<MonederoService.MovimientoBE> RecargarAsync(MonederoService.RecargaBE recarga);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonederosService/Extornar", ReplyAction="http://tempuri.org/IMonederosService/ExtornarResponse")]
        MonederoService.MovimientoBE Extornar(MonederoService.ExtornoBE extorno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonederosService/Extornar", ReplyAction="http://tempuri.org/IMonederosService/ExtornarResponse")]
        System.Threading.Tasks.Task<MonederoService.MovimientoBE> ExtornarAsync(MonederoService.ExtornoBE extorno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonederosService/Pagar", ReplyAction="http://tempuri.org/IMonederosService/PagarResponse")]
        MonederoService.MovimientoBE Pagar(MonederoService.PagoBE pago);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonederosService/Pagar", ReplyAction="http://tempuri.org/IMonederosService/PagarResponse")]
        System.Threading.Tasks.Task<MonederoService.MovimientoBE> PagarAsync(MonederoService.PagoBE pago);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonederosService/Saldo", ReplyAction="http://tempuri.org/IMonederosService/SaldoResponse")]
        MonederoService.MovimientoBE Saldo([System.ServiceModel.MessageParameterAttribute(Name="saldo")] MonederoService.SaldoBE saldo1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonederosService/Saldo", ReplyAction="http://tempuri.org/IMonederosService/SaldoResponse")]
        System.Threading.Tasks.Task<MonederoService.MovimientoBE> SaldoAsync(MonederoService.SaldoBE saldo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMonederosServiceChannel : MonederoService.IMonederosService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MonederosServiceClient : System.ServiceModel.ClientBase<MonederoService.IMonederosService>, MonederoService.IMonederosService {
        
        public MonederosServiceClient() {
        }
        
        public MonederosServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MonederosServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonederosServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonederosServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MonederoService.MovimientoBE Recargar(MonederoService.RecargaBE recarga) {
            return base.Channel.Recargar(recarga);
        }
        
        public System.Threading.Tasks.Task<MonederoService.MovimientoBE> RecargarAsync(MonederoService.RecargaBE recarga) {
            return base.Channel.RecargarAsync(recarga);
        }
        
        public MonederoService.MovimientoBE Extornar(MonederoService.ExtornoBE extorno) {
            return base.Channel.Extornar(extorno);
        }
        
        public System.Threading.Tasks.Task<MonederoService.MovimientoBE> ExtornarAsync(MonederoService.ExtornoBE extorno) {
            return base.Channel.ExtornarAsync(extorno);
        }
        
        public MonederoService.MovimientoBE Pagar(MonederoService.PagoBE pago) {
            return base.Channel.Pagar(pago);
        }
        
        public System.Threading.Tasks.Task<MonederoService.MovimientoBE> PagarAsync(MonederoService.PagoBE pago) {
            return base.Channel.PagarAsync(pago);
        }
        
        public MonederoService.MovimientoBE Saldo(MonederoService.SaldoBE saldo1) {
            return base.Channel.Saldo(saldo1);
        }
        
        public System.Threading.Tasks.Task<MonederoService.MovimientoBE> SaldoAsync(MonederoService.SaldoBE saldo) {
            return base.Channel.SaldoAsync(saldo);
        }
    }
}
